project:
  name: quickstart-intersystems-iris
  regions:
  - us-east-1
tests:
  default:
    template: ./templates/iris-master.template.yaml
    regions:
    - us-east-1
    parameters:
      IRISPasswordParameter: demo
      AvailabilityZones: 'us-east-1a,us-east-1b,us-east-1c'
      RemoteAccessCIDRParameter: 0.0.0.0/0
      VPCCIDR: 10.0.0.0/16
      PrivateSubnet1CIDR: 10.0.1.0/24
      PrivateSubnet2CIDR: 10.0.2.0/24
      PrivateSubnet3CIDR: 10.0.3.0/24
      InstanceTypeParameter: m5.large
      S3BucketNameParameter: iris-distr
      SshKeyParameter: ec2
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      QSS3KeyPrefix: quickstart-intersystems-iris/