// Add steps as necessary for accessing the software, post-configuration, and testing. Don’t include full usage instructions for your software, but add links to your product documentation for that information.
//Should any sections not be applicable, remove them
== Post-deployment steps

=== Test the deployment
// If steps are required to test the deployment, add them here. If not, remove the heading

. Connect to IRIS node 1 using the bastion host (replacing bracketed text).

[source,bash]
----
$ chmod 400 <my-ec2-key>.pem
$ ssh-add <my-ec2-key>.pem
$ ssh -J ec2-user@<bastion-public-ip> ec2-user@<node01-private-ip> -L 52773:<node01-private-ip>:52773
----

The IRIS Management Portal for the instance should be available at http://localhost:52773/csp/sys/%25CSP.Portal.Home.zen with the following credentials:

//This is a private URL that works only from within the deployed environment.

* User: SuperUser
* Password: <password you entered at stack creation>

[start=2]
. Navigate to **System Administration**, **Configuration**, **Mirror Settings**, **Edit Mirror**.  Make sure that the system is configured with two failover members.

. Navigate to **System Administration**, **Configuration**, **Local Databases**. Verify that the mirrored database is created and active.

. Following https://docs.intersystems.com/irislatest/csp/docbook/DocBook.UI.Page.cls?KEY=AFL_jdbc[First Look JDBC and InterSystems Databases^], validate JDBC connectivity to IRIS using the load balancer. Change the URL variable to the value displayed in the template output, and change the password from **SYS** to the one you selected during setup.

=== Failover test

This Quick Start is architected to be highly available. This means that the site remains available in the case of an instance or Availability Zone failure. To verify high availability, follow these steps to simulate a failure and perform a failover test.

. On node 2, navigate to the **Management Portal** (see <<Test the deployment>> section earlier). 

. Open the **Configuration**, **Edit Mirror** page. At the bottom of the page you should see "This member is the backup. Changes must be made on the primary."

. Locate the node 1 instance in the Amazon EC2 management dashboard. Its name has the format `MyStackName-Node01-1NG<XXXXXX>`.

. Restart the node 1 instance. This will simulate an instance or Availability Zone outage.

. Reload the node 2 **Edit Mirror** page. The status should change to this: "This member is the primary. Changes will be sent to other members."