// Add any tips or answers to anticipated questions. This could include the following troubleshooting information. If you don’t have any other Q&A to add, change “FAQ” to “Troubleshooting.”

== FAQ

*Q.* I encountered a *CREATE_FAILED* error when I launched the Quick Start.

*A.* If AWS CloudFormation fails to create the stack, relaunch the template with *Rollback on failure* set to *Disabled*. This setting is under *Advanced* in the AWS CloudFormation console on the *Configure stack options* page. With this setting, the stack’s state is retained, and the instance keeps running so that you can troubleshoot the issue. The log files `cloud-init.log` and `cloud-init-output.log` are located at `/var/log/`.

// Since we’re deploying on Linux instances, Dave provided the location for log files on Linux in the preceding sentence.

WARNING: When you set *Rollback on failure* to *Disabled*, you continue to incur AWS charges for this stack. Delete the stack when you finish troubleshooting.

For additional information, see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/troubleshooting.html[Troubleshooting AWS CloudFormation^] on the AWS website.

*Q.* I encountered a size limitation error when I deployed the AWS CloudFormation templates.

*A.* We recommend that you launch the Quick Start templates from the links in this guide or from another S3 bucket. If you deploy the templates from a local copy on your computer or from a location other than an S3 bucket, you might encounter template size limitations. For more information, see http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html[AWS CloudFormation quotas^].

*Q.* The stack is being created, and I can't access IRIS.

*A.* You probably simply need to wait. It takes approximately two minutes from the moment the EC2 instance status says **CREATE COMPLETED** to the moment IRIS is fully available. 


== Troubleshooting

The IRIS Management Portal for the instance should be available at `http://localhost:52773/csp/sys/%25CSP.Portal.Home.zen` Credentials - User: SuperUser, and the password you entered at stack creation.
If the IRIS Management Portal is inaccessible, troubleshooting the IRIS installation can be done from the command line.

. For command-line access, connect to the IRIS nodes using the bastion host (replacing the bracketed text):

[source,bash]
----
$ chmod 400 <my-ec2-key>.pem
$ ssh-add <my-ec2-key>.pem
$ ssh -J ec2-user@<bastion-public-ip> ec2-user@<node-private-ip> -L 52773:<node-private-ip>:52773
----

[start=2]
. Connect to the EC2 node instances by using SSH. Verify that IRIS is running:

[source,bash]
$iris list

[start=3]
. If you don't see any active IRIS instances, or if the message `iris: command not found` appears, then IRIS installation has failed. View this log file on the instance to identify any problems with the IRIS installation during instance first start:

[source,bash]
$cat /var/log/cloud-init-output.log

[start=4]
. To connect to the IRIS command prompt use:

[source,bash]
$ iris session iris

Consult the https://docs.intersystems.com/irislatest/csp/docbook/DocBook.UI.Page.cls?KEY=GCM[InterSystems IRIS Management and Monitoring guide^].

Contact InterSystems Support.

If EC2 instances are not available or reachable, contact AWS Support. 