// If no preperation is required, remove all content from here

==== Prepare your AWS account

To access the EC2 instances provisioned by this quickstart, you will need at least one EC2 key pair. Refer to this guide for details: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html

//TODO Dave, I think that the key-pair blurb is now generated dynamically from the latest boilerplate when applicable. Can we delete the above paragraph?

==== Aquire {partner-product-name} binaries and license key

InterSystems IRIS binaries are available to InterSystems customers at https://wrc.intersystems.com/. Log in with your InterSystems Worldwide Response Center (WRC) credentials and follow the links to **Actions**, **SW Distributions**, **InterSystems IRIS**. This Quick Start deployment guide is written for the InterSystems IRIS 2020.1 build 215. IRIS binaries file names are of the format `ISCAgent-2020.1.0.215.0-lnxrhx64.tar.gz` and `IRIS-2020.1.0.215.1-lnxrhx64.tar.gz`.

You should be able to use your existing InterSystems IRIS license key (iris.key) or request one from the https://evaluation.intersystems.com/[IRIS Evaluation Service^]. The Quick Start requires the noncontainer version of the key and binaries. 

Nonregistered customers can https://www.intersystems.com/who-we-are/contact-us/[contact InterSystems^].


==== Prepare for the deployment

. Create an S3 bucket. 
. Copy the IRIS binaries files and iris.key (replacing the bracketed text with your bucket name):

[source,bash]
----
BUCKET=<my bucket>
aws s3 mb s3://$BUCKET
aws s3 cp ISCAgent-2020.1.0.215.0-lnxrhx64.tar.gz s3://$BUCKET
aws s3 cp IRIS-2020.1.0.215.1-lnxrhx64.tar.gz s3://$BUCKET
aws s3 cp iris.key s3://$BUCKET
----