---
AWSTemplateFormatVersion: 2010-09-09
Metadata:
    Author: Anton Umnikov
    Last Updated: August 12, 2020
    Description: IRIS Bastion Node

Parameters:
  VpcIdParameter:
    Description: Launch EC2 instances in this VPC
    Default: vpc-029aba04d6dbcfae4
    Type: AWS::EC2::VPC::Id
  InstanceSubnetIdParameter:
    Description: Launch EC2 instances in this subnet
    Default: subnet-024ee9bc8ba573050
    Type: AWS::EC2::Subnet::Id
  #InstanceSecurityGroupParameter:
  #  Description:  Security group for the instance
  #  Type: AWS::EC2::SecurityGroup::Id
  RemoteAccessCIDRParameter:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: Restrict to <your-own-ip>/32 for better security
    Default: 0.0.0.0/0
    Type: String

  SshKeyParameter:
    Description: SSH Keypair to login to the instance
    Default: anton-isc
    Type: AWS::EC2::KeyPair::KeyName
  InstanceTypeParameter:
    Description: Cluster node instance type
    Type: String
    Default: t3.small
    AllowedValues: 
      - t3.small
      - t3.large
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow selected CIDR block to access port 22
      GroupName: !Sub "${AWS::StackName}-Bastion-SG"
      VpcId: !Ref VpcIdParameter
  SecurityGroupIngressSSH:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref InstanceSecurityGroup
      IpProtocol: TCP
      FromPort: 22
      ToPort: 22
      CidrIp: !Ref RemoteAccessCIDRParameter
  ##Node Start##         
  NodeInstance:
    Type: AWS::EC2::Instance
    Properties:
      Tags: 
        - 
          Key: Name
          Value: !Sub "${AWS::StackName}-Bastion"
      ImageId: !Ref LatestAmiId
        #Fn::FindInMap:
        #- RegionMap
        #- Ref: AWS::Region
        #- AMIx64
      InstanceType: !Ref InstanceTypeParameter
      KeyName: !Ref SshKeyParameter
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      SubnetId: !Ref InstanceSubnetIdParameter

Outputs:
  NodePublicIP:
    Description: Node PublicIP
    Value: !Join
      - ''
      - ['', !GetAtt NodeInstance.PublicIp, '']
